[2025-07-28T11:38:31.372+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: run_crawler_hourly.run_crawler manual__2025-07-28T11:38:30.747813+00:00 [queued]>
[2025-07-28T11:38:31.380+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: run_crawler_hourly.run_crawler manual__2025-07-28T11:38:30.747813+00:00 [queued]>
[2025-07-28T11:38:31.380+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-07-28T11:38:31.393+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): run_crawler> on 2025-07-28 11:38:30.747813+00:00
[2025-07-28T11:38:31.399+0000] {standard_task_runner.py:57} INFO - Started process 1119 to run task
[2025-07-28T11:38:31.401+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'run_crawler_hourly', 'run_crawler', 'manual__2025-07-28T11:38:30.747813+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/crawl_every_hour.py', '--cfg-path', '/tmp/tmpryl1wlar']
[2025-07-28T11:38:31.403+0000] {standard_task_runner.py:85} INFO - Job 9: Subtask run_crawler
[2025-07-28T11:38:31.453+0000] {task_command.py:415} INFO - Running <TaskInstance: run_crawler_hourly.run_crawler manual__2025-07-28T11:38:30.747813+00:00 [running]> on host 00b4b9fb4b52
[2025-07-28T11:38:31.535+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='apoorhass@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='run_crawler_hourly' AIRFLOW_CTX_TASK_ID='run_crawler' AIRFLOW_CTX_EXECUTION_DATE='2025-07-28T11:38:30.747813+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-28T11:38:30.747813+00:00'
[2025-07-28T11:38:31.547+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 197, in execute
    raise AirflowException(f"Can not find the cwd: {self.cwd}")
airflow.exceptions.AirflowException: Can not find the cwd: /home/astane/Desktop/Sahab/docker
[2025-07-28T11:38:31.551+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=run_crawler_hourly, task_id=run_crawler, execution_date=20250728T113830, start_date=20250728T113831, end_date=20250728T113831
[2025-07-28T11:38:31.561+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 9 for task run_crawler (Can not find the cwd: /home/astane/Desktop/Sahab/docker; 1119)
[2025-07-28T11:38:31.573+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-07-28T11:38:31.591+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
